### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by snorlaxse** [coneycode/hexo-git-backup#24]
```
backup:
    type: git
    theme: indigo
    repository:
      github: git@github.com:Captainzj/hexo_backup.git,master
      gitcafe: git@github.com:Captainzj/hexo_backup.git,master
```
```
➜  _posts git:(master) ssh -T git@github.com
Hi Captainzj! You've successfully authenticated, but GitHub does not provide shell access.
➜  _posts git:(master) ✗ git remote -v
gitcafe	git@github.com:Captainzj/hexo_backup.git (fetch)
gitcafe	git@github.com:Captainzj/hexo_backup.git (push)
github	git@github.com:Captainzj/hexo_backup.git (fetch)
github	git@github.com:Captainzj/hexo_backup.git (push)
➜  _posts git:(master) ✗ sudo hexo b
INFO  Start backup: git
[master f05cad9] Site updated: 2018-11-19 22:20:37
 1 file changed, 2 insertions(+), 3 deletions(-)
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git
```
我试了已解决的几种方法，但依旧不能备份成功
